services:
  nodeasup:
    build: .
    container_name: nodeasup
    ports:
      - "8001:8001"
    volumes:
      - ./backend/aiconfig.yaml:/app/backend/aiconfig.yaml:ro
      - ./data:/app/backend/data
    restart: unless-stopped
    networks:
      - ontap_shared

networks:
  ontap_shared:
    name: ontappowertoys_default
    external: true
